apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
# deployment
spec:
  selector:
    # match pod
    matchLabels:
      app: vproapp
  replicas: 1
  # def pod
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      # def cons
      containers:
        - name: vproapp
          image: vprofile/vprofileapp:V1
          ports:
            - name: vproapp-port
              containerPort: 8080
      # helper cons, first run these, after finished, death, then run main cons
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;",
            ]

        - name: init-memcache
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcache; sleep 2; done;",
            ]
