apiVersion: v1
kind: Service
metadata:
  # should match vprofile project java src/main/resources/application.properties file
  name: vprodb
# cluster IP
spec:
  ports:
    - port: 3306
      # port name defined in db.yaml
      targetPort: vprodb-port
      protocol: TCP
  selector:
    # match deployment name
    app: vprodb
  type: ClusterIP
