apiVersion: v1
kind: Service
metadata:
  # should match vprofile project java src/main/resources/application.properties file
  name: vprocache01
# cluster IP
spec:
  ports:
    - port: 11211
      # port name defined in memcache.yaml
      targetPort: vpromc-port
      protocol: TCP
  # match deployment name
  selector:
    app: vpromc
  type: ClusterIP
