apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
# deployment
spec:
  selector:
    # match pod
    matchLabels:
      app: vpromq01
  replicas: 1
  # def pod
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      # def cons
      containers:
        - name: vpromq01
          image: rabbitmq:latest
          ports:
            - name: vpromq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              # from app-secret.yaml
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
