apiVersion: v1
kind: Service
metadata:
  # should match vprofile project java src/main/resources/application.properties file
  name: vprocache01
# cluster IP
spec:
  ports:
    - port: 15672
      # port name defined in rmq-dep
      targetPort: vpromq-port
      protocol: TCP
  selector:
    app: vpromq01
  type: ClusterIP
